### ISSUE TITLE
Working fine, but...

### ISSUE THREAD

**Issue by Dirk23** [l3akage/otrs2slack#1]
Hi,

i realy like your small littel script and its realy working fine, but i wanted to modify your script for to get more information i.e. when some one closes the ticket, oder locks it. So i needed to change the DB Select and the Message it is sending. I checked out that the select is working and changed it in the script. Saddly i get no message from OTRS in Slack.

Is there a way to debug the script, or is there a way to let the script run without triggering it from OTRS?

**Comment by l3akage** [comment]
Hi,

yea OTRS just calls the script via command line so you could trigger it youself with
`ruby /opt/otrs2slack.rb tn foo`
where tn is the ticketnumber according to the tn field in the database and foo is just a random parameter so the script doesn't exit
`exit if ARGV.size != 2`

If you fork the repo and publish your changes i could take a look at it

**Comment by Dirk23** [comment]
Thank you for your offer to help, but i think i did it. I guess there was something wrong with my SQL syntax, so the script stopped to run.

**Comment by Dirk23** [comment]
Maybe i have one more thing :)

I would like to show ticket priority in Slack Message and i changed the SQL Query, so i get the piority as value 1-5 from #{row['ticket_priority_id']}

i tried this, but had no luck at all:

```
if  #{row['ticket_priority_id']} == 1
prio = "very-low"
elseif #{row['ticket_priority_id']} == 2
prio = "low"
elseif #{row['ticket_priority_id']} == 3
prio = "normal"
elseif #{row['ticket_priority_id']} == 4
prio = "high"
elseif#{row['ticket_priority_id']} == 5
prio = "very-high"
end
```

prio seems to be empty all the time!

**Comment by l3akage** [comment]
`#{..}` only works in strings surrounded by " and row['ticket_priority_id'] returns a string so "1" == 1 is false.

you could do

```
prio = case row['ticket_priority_id'].to_i
       when 1
         'very-low'
       when 2
         'low'
       when 3
         'normal'
       when 4
         'high'
       when 5
         'very-high'
       else
         'none'
       end
```

or shorter

```
priorities = %w(very-low low normal high very-high)
prio = priorities[row['ticket_priority_id'].to_i - 1] || 'none'
```

**Comment by Dirk23** [comment]
Works like a charm. Thank you.
And one other thing: Do you know how to submit a payload instead of a String? I would like to add an attachment to the Message like [described here](https://api.slack.com/docs/message-attachments)

```
{
    "attachments": [
        {
            "fallback": "New ticket from Andrea Lee - Ticket #1943: Can't rest my password - https://groove.hq/path/to/ticket/1943",
            "pretext": "New ticket from Andrea Lee",
            "title": "Ticket #1943: Can't reset my password",
            "title_link": "https://groove.hq/path/to/ticket/1943",
            "text": "Help! I tried to reset my password but nothing happened!",
            "color": "#7CD197"
        }
    ]
}
```
